//{{NO_DEPENDENCIES}}
// Include files generated by Microsoft Visual C++.
// Used in CC_Tool.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             101
#define IDD_CC_TOOL_FORM                102
#define IDR_MAINFRAME                   128
#define IDR_CC_ToolTYPE                 129
#define IDD_DIALOG_EDIT_NUM             130
#define IDD_DIALOG_PLAN                 132
#define IDC_STATIC_GRAPH                1000
#define IDC_COMBO_GRAPH                 1001
#define IDC_LIST_SERIAL                 1002
#define IDC_BUTTON_EXP_DOWN             1003
#define IDC_BUTTON_EXP_UP               1004
#define IDC_EDIT_EXPTIME                1005
#define IDC_BUTTON_EXP_UPDATE           1006
#define IDC_LIST_DATA                   1007
#define IDC_BUTTON_GET_DATA             1008
#define IDC_BUTTON_DEL                  1009
#define IDC_BUTTON_REF_DATA             1010
#define IDC_BUTTON_SAVE_CSV             1011
#define IDC_EDIT_NUM                    1013
#define IDC_BUTTON_REFSAMPLE            1014
#define IDC_COMBO_AVERAGE               1016
#define IDC_BUTTON1                     1017
#define IDC_BUTTON_REDETECT             1017
#define IDC_BUTTON_PLAN_START           1017
#define IDC_STATIC_EXPNAME              1018
#define IDC_BUTTON_PLAN_STOP            1018
#define IDC_STATIC_AVGNAME              1019
#define IDC_STATIC_DLIST_NAME           1020
#define IDC_CHECK_REPEAT                1021
#define IDC_EDIT_REPEATTIME             1022
#define IDC_BUTTON_PLAN                 1023
#define IDC_STATIC_TIME                 1025
#define IDC_RADIO_METHOD1               1026
#define IDC_RADIO_METHOD2               1027
#define IDC_COMBO_EVERYTIME             1028
#define IDC_EDIT_PLAN_INTERVAL          1030
#define IDC_EDIT2                       1031
#define ID_DO_DARK                      1032
#define IDC_EDIT_AVG_INTERVAL           1033
#define IDC_CHECK_LIMIT_CLOCK           1033
#define IDC_EDIT_LIMIT_CLOCK1           1034
#define IDC_EDIT_LIMIT_CLOCK2           1035
#define IDC_EDIT_LIMIT_CLOCK3           1036
#define IDC_EDIT_LIMIT_CLOCK4           1037
#define IDC_CHECK_LIMIT_CLOCK2          1038
#define IDC_CHECK_AUTO_SAVE             1038

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1039
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
